import './globals.css';
import type { Metadata } from 'next';
import Navigation from '@/app/components/navigation/navigation';
import Footer from '@/app/components/footer/footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
        <Footer></Footer>
      </body>
    </html>
  )
}
